//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonu.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelOtomasyonEntities : DbContext
    {
        public HotelOtomasyonEntities()
            : base("name=HotelOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TOda> TOda { get; set; }
        public virtual DbSet<TTelefon> TTelefon { get; set; }
        public virtual DbSet<TUrunGrup> TUrunGrup { get; set; }
        public virtual DbSet<TBirim> TBirim { get; set; }
        public virtual DbSet<TDepartman> TDepartman { get; set; }
        public virtual DbSet<TDurum> TDurum { get; set; }
        public virtual DbSet<TGorev> TGorev { get; set; }
        public virtual DbSet<TIl> TIl { get; set; }
        public virtual DbSet<TIlce> TIlce { get; set; }
        public virtual DbSet<TKasa> TKasa { get; set; }
        public virtual DbSet<TKur> TKur { get; set; }
        public virtual DbSet<TMisafir> TMisafir { get; set; }
        public virtual DbSet<TPersonel> TPersonel { get; set; }
        public virtual DbSet<TUlke> TUlke { get; set; }
        public virtual DbSet<TUrun> TUrun { get; set; }
        public virtual DbSet<THareket> THareket { get; set; }
        public virtual DbSet<TRezervasyon> TRezervasyon { get; set; }
        public virtual DbSet<TKullaniciSite> TKullaniciSite { get; set; }
        public virtual DbSet<TKMesajSite> TKMesajSite { get; set; }
        public virtual DbSet<TMesajSite> TMesajSite { get; set; }
    
        public virtual ObjectResult<OdaDurum_Result> OdaDurum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OdaDurum_Result>("OdaDurum");
        }
    }
}
