//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKur
    {
        public byte KurID { get; set; }
        public string Ad { get; set; }
        public string Sembol { get; set; }
        public Nullable<decimal> Deger { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<byte> Durum { get; set; }
    
        public virtual TDurum TDurum { get; set; }
    }
}
