//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPersonel
    {
        public byte PersonelID { get; set; }
        public string Personel { get; set; }
        public string TC { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
        public Nullable<byte> Departman { get; set; }
        public Nullable<byte> Gorev { get; set; }
        public string Aciklama { get; set; }
        public string KimlikOn { get; set; }
        public string KimlikArka { get; set; }
        public string Yetki { get; set; }
        public string Sifre { get; set; }
        public Nullable<byte> Durum { get; set; }
    
        public virtual TDepartman TDepartman { get; set; }
        public virtual TDurum TDurum { get; set; }
        public virtual TGorev TGorev { get; set; }
    }
}
