//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTelefon
    {
        public byte TelefonID { get; set; }
        public string Aciklama { get; set; }
        public string Telefon { get; set; }
        public Nullable<byte> Durum { get; set; }
    
        public virtual TDurum TDurum { get; set; }
        public virtual TDurum TDurum1 { get; set; }
    }
}
