//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUrun()
        {
            this.THareket = new HashSet<THareket>();
        }
    
        public byte UrunID { get; set; }
        public string Urun { get; set; }
        public Nullable<byte> UrunGrup { get; set; }
        public Nullable<byte> Birim { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<byte> Kdv { get; set; }
        public Nullable<byte> Durum { get; set; }
    
        public virtual TBirim TBirim { get; set; }
        public virtual TDurum TDurum { get; set; }
        public virtual TUrunGrup TUrunGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THareket> THareket { get; set; }
    }
}
